// <auto-generated />
using System;
using AngularChatApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AngularChatApp.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20221012182754_model change back back")]
    partial class modelchangebackback
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AngularChatApp.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("691a8091-74da-4379-90ed-c15f6d1ca05e"),
                            Password = "wachtwoord",
                            name = "maxim",
                            username = "maximeke"
                        },
                        new
                        {
                            UserId = new Guid("ff5dcf60-c352-4556-b6fc-858fad0a680e"),
                            Password = "wachtwoord2",
                            name = "vincent",
                            username = "achterlijken"
                        },
                        new
                        {
                            UserId = new Guid("1cf0cdb3-959b-4e0f-b433-43926e108735"),
                            Password = "wimpie2000",
                            name = "Wim",
                            username = "Wimpie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
