// <auto-generated />
using System;
using AngularChatApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AngularChatApp.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20221012181731_model change back")]
    partial class modelchangeback
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AngularChatApp.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("995c1479-155b-426f-813f-e69e56774974"),
                            Password = "wachtwoord",
                            name = "maxim",
                            username = "maximeke"
                        },
                        new
                        {
                            UserId = new Guid("b16e2cf4-6c84-4643-bda0-d8976b8d989d"),
                            Password = "wachtwoord2",
                            name = "vincent",
                            username = "achterlijken"
                        },
                        new
                        {
                            UserId = new Guid("fab45b78-bdc9-4f61-9c6b-4ae73dde7ceb"),
                            Password = "wimpie2000",
                            name = "Wim",
                            username = "Wimpie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
