// <auto-generated />
using System;
using AngularChatApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AngularChatApp.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20221012181414_model change test")]
    partial class modelchangetest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AngularChatApp.Models.Usertest", b =>
                {
                    b.Property<Guid>("UsertestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsertestId");

                    b.ToTable("Usertest");

                    b.HasData(
                        new
                        {
                            UsertestId = new Guid("ab41fe7f-9c08-4e2f-8f4d-9efeb47431b8"),
                            Password = "wachtwoord",
                            name = "maxim",
                            username = "maximeke"
                        },
                        new
                        {
                            UsertestId = new Guid("12a7f862-4b56-4ad0-a22a-5bf82d3a9b42"),
                            Password = "wachtwoord2",
                            name = "vincent",
                            username = "achterlijken"
                        },
                        new
                        {
                            UsertestId = new Guid("5b1cca4e-17a2-4c14-8cb1-4dd2d7158c92"),
                            Password = "test",
                            name = "test",
                            username = "testt"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
